-- CreateEnum
CREATE TYPE "ReservationStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "GenderOrder" AS ENUM ('MALES_FIRST', 'FEMALES_FIRST');

-- CreateEnum
CREATE TYPE "SyncStatus" AS ENUM ('PENDING', 'SYNCED', 'FAILED', 'CONFLICT');

-- CreateTable
CREATE TABLE "clubs" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "secret" TEXT NOT NULL,
    "secretValidFrom" TIMESTAMP(3) NOT NULL,
    "secretValidUntil" TIMESTAMP(3) NOT NULL,
    "logoUrl" TEXT,
    "primaryColor" TEXT,
    "secondaryColor" TEXT,
    "timezone" TEXT NOT NULL DEFAULT 'Europe/Helsinki',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "clubs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "islands" (
    "id" TEXT NOT NULL,
    "clubId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "numberOfSaunas" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "islands_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "saunas" (
    "id" TEXT NOT NULL,
    "islandId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "heatingTimeHours" INTEGER NOT NULL DEFAULT 2,
    "autoClubSaunaEnabled" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "saunas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "boats" (
    "id" TEXT NOT NULL,
    "clubId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "membershipNumber" TEXT NOT NULL,
    "captainName" TEXT,
    "phoneNumber" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "boats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reservations" (
    "id" TEXT NOT NULL,
    "saunaId" TEXT NOT NULL,
    "boatId" TEXT NOT NULL,
    "startTime" TIMESTAMP(3) NOT NULL,
    "endTime" TIMESTAMP(3) NOT NULL,
    "adults" INTEGER NOT NULL,
    "kids" INTEGER NOT NULL DEFAULT 0,
    "status" "ReservationStatus" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "cancelledAt" TIMESTAMP(3),

    CONSTRAINT "reservations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "shared_reservations" (
    "id" TEXT NOT NULL,
    "saunaId" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "startTime" TIME NOT NULL,
    "malesDurationHours" INTEGER NOT NULL,
    "femalesDurationHours" INTEGER NOT NULL,
    "genderOrder" "GenderOrder" NOT NULL,
    "name" TEXT,
    "description" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "autoCancelledAt" TIMESTAMP(3),
    "convertedToIndividual" BOOLEAN NOT NULL DEFAULT false,
    "createdBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "shared_reservations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "shared_reservation_participants" (
    "id" TEXT NOT NULL,
    "sharedReservationId" TEXT NOT NULL,
    "boatId" TEXT NOT NULL,
    "adults" INTEGER NOT NULL,
    "kids" INTEGER NOT NULL DEFAULT 0,
    "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "shared_reservation_participants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "island_devices" (
    "id" TEXT NOT NULL,
    "islandId" TEXT NOT NULL,
    "deviceToken" TEXT NOT NULL,
    "deviceName" TEXT,
    "isConfigured" BOOLEAN NOT NULL DEFAULT false,
    "lastSyncAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "island_devices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sync_logs" (
    "id" TEXT NOT NULL,
    "islandId" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "operation" TEXT NOT NULL,
    "dataSnapshot" JSONB NOT NULL,
    "status" "SyncStatus" NOT NULL DEFAULT 'PENDING',
    "errorMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "syncedAt" TIMESTAMP(3),

    CONSTRAINT "sync_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "admin_users" (
    "id" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "name" TEXT,
    "email" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "lastLoginAt" TIMESTAMP(3),

    CONSTRAINT "admin_users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "clubs_secret_key" ON "clubs"("secret");

-- CreateIndex
CREATE INDEX "clubs_secret_idx" ON "clubs"("secret");

-- CreateIndex
CREATE INDEX "islands_clubId_idx" ON "islands"("clubId");

-- CreateIndex
CREATE INDEX "saunas_islandId_idx" ON "saunas"("islandId");

-- CreateIndex
CREATE INDEX "boats_clubId_idx" ON "boats"("clubId");

-- CreateIndex
CREATE INDEX "boats_membershipNumber_idx" ON "boats"("membershipNumber");

-- CreateIndex
CREATE UNIQUE INDEX "boats_clubId_membershipNumber_key" ON "boats"("clubId", "membershipNumber");

-- CreateIndex
CREATE INDEX "reservations_saunaId_startTime_idx" ON "reservations"("saunaId", "startTime");

-- CreateIndex
CREATE INDEX "reservations_boatId_idx" ON "reservations"("boatId");

-- CreateIndex
CREATE INDEX "reservations_startTime_idx" ON "reservations"("startTime");

-- CreateIndex
CREATE INDEX "shared_reservations_saunaId_date_idx" ON "shared_reservations"("saunaId", "date");

-- CreateIndex
CREATE INDEX "shared_reservations_date_idx" ON "shared_reservations"("date");

-- CreateIndex
CREATE INDEX "shared_reservations_isAutoGenerated_idx" ON "shared_reservations"("isAutoGenerated");

-- CreateIndex
CREATE INDEX "shared_reservation_participants_sharedReservationId_idx" ON "shared_reservation_participants"("sharedReservationId");

-- CreateIndex
CREATE INDEX "shared_reservation_participants_boatId_idx" ON "shared_reservation_participants"("boatId");

-- CreateIndex
CREATE UNIQUE INDEX "shared_reservation_participants_sharedReservationId_boatId_key" ON "shared_reservation_participants"("sharedReservationId", "boatId");

-- CreateIndex
CREATE UNIQUE INDEX "island_devices_islandId_key" ON "island_devices"("islandId");

-- CreateIndex
CREATE UNIQUE INDEX "island_devices_deviceToken_key" ON "island_devices"("deviceToken");

-- CreateIndex
CREATE INDEX "island_devices_deviceToken_idx" ON "island_devices"("deviceToken");

-- CreateIndex
CREATE INDEX "sync_logs_islandId_status_idx" ON "sync_logs"("islandId", "status");

-- CreateIndex
CREATE INDEX "sync_logs_createdAt_idx" ON "sync_logs"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "admin_users_username_key" ON "admin_users"("username");

-- AddForeignKey
ALTER TABLE "islands" ADD CONSTRAINT "islands_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saunas" ADD CONSTRAINT "saunas_islandId_fkey" FOREIGN KEY ("islandId") REFERENCES "islands"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "boats" ADD CONSTRAINT "boats_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_saunaId_fkey" FOREIGN KEY ("saunaId") REFERENCES "saunas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_boatId_fkey" FOREIGN KEY ("boatId") REFERENCES "boats"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shared_reservations" ADD CONSTRAINT "shared_reservations_saunaId_fkey" FOREIGN KEY ("saunaId") REFERENCES "saunas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shared_reservation_participants" ADD CONSTRAINT "shared_reservation_participants_sharedReservationId_fkey" FOREIGN KEY ("sharedReservationId") REFERENCES "shared_reservations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shared_reservation_participants" ADD CONSTRAINT "shared_reservation_participants_boatId_fkey" FOREIGN KEY ("boatId") REFERENCES "boats"("id") ON DELETE CASCADE ON UPDATE CASCADE;
