import { NextRequest } from 'next/server';
import {
  parseRequestBody,
  successResponse,
  errorResponse,
  handleApiError,
} from '@/lib/api-utils';
import prisma from '@/lib/db';

/**
 * POST /api/sync/device
 * Bidirectional sync between Island Device and backend
 * Island Device is the source of truth - device data always wins
 *
 * This is a convenience endpoint that combines push and pull in one request.
 * For most cases, clients should use /api/sync/push and /api/sync/pull separately.
 */
export async function POST(request: NextRequest) {
  try {
    const body = (await parseRequestBody(request)) as {
      deviceId?: string;
      islandId?: string;
      changes?: Array<{
        id: string;
        entityType: string;
        entityId: string;
        operation: string;
        data: Record<string, unknown>;
      }>;
      lastSyncTimestamp?: string;
    };
    const { deviceId, islandId, changes = [], lastSyncTimestamp } = body;

    if (!deviceId || typeof deviceId !== 'string') {
      return errorResponse('deviceId is required', 400);
    }

    if (!islandId || typeof islandId !== 'string') {
      return errorResponse('islandId is required', 400);
    }

    // Verify device is authorized for this island
    const device = await prisma.islandDevice.findUnique({
      where: { id: deviceId },
    });

    if (!device) {
      return errorResponse('Device not found', 404);
    }

    if (device.islandId !== islandId) {
      return errorResponse('Device not authorized for this island', 403);
    }

    // Step 1: Process device changes (push to backend)
    const appliedChanges: string[] = [];
    const rejectedChanges: Array<{ id: string; reason: string }> = [];

    if (changes.length > 0) {
      // Use the same logic as /api/sync/push
      // Import and reuse the handler functions
      const { default: pushHandler } = await import('../push/route');

      const pushResponse = await pushHandler(request);
      const pushData = await pushResponse.json();

      if (pushData.success && pushData.data) {
        appliedChanges.push(...pushData.data.appliedChanges);
        rejectedChanges.push(...pushData.data.rejectedChanges);
      }
    }

    // Step 2: Get backend changes to send to device (pull)
    const since = lastSyncTimestamp
      ? new Date(lastSyncTimestamp)
      : new Date(Date.now() - 24 * 60 * 60 * 1000); // Last 24 hours

    const island = await prisma.island.findUnique({
      where: { id: islandId },
      include: { saunas: true },
    });

    if (!island) {
      return errorResponse('Island not found', 404);
    }

    const saunaIds = island.saunas.map((s) => s.id);

    // Get reservations modified since last sync
    const reservations = await prisma.reservation.findMany({
      where: {
        saunaId: { in: saunaIds },
        OR: [{ createdAt: { gte: since } }, { updatedAt: { gte: since } }],
      },
      orderBy: { createdAt: 'asc' },
    });

    // Get shared reservations
    const sharedReservations = await prisma.sharedReservation.findMany({
      where: {
        saunaId: { in: saunaIds },
        OR: [{ createdAt: { gte: since } }, { updatedAt: { gte: since } }],
      },
      include: { participants: true },
      orderBy: { createdAt: 'asc' },
    });

    // Format server changes
    const serverChanges = [
      ...reservations.map((r) => ({
        id: crypto.randomUUID(),
        entityType: 'reservation' as const,
        entityId: r.id,
        operation: 'create' as const,
        data: {
          id: r.id,
          saunaId: r.saunaId,
          boatId: r.boatId,
          startTime: r.startTime.toISOString(),
          endTime: r.endTime.toISOString(),
          adults: r.adults,
          kids: r.kids,
          status: r.status,
          createdAt: r.createdAt.toISOString(),
          cancelledAt: r.cancelledAt?.toISOString() || null,
        },
        timestamp: r.updatedAt,
      })),
      ...sharedReservations.flatMap((sr) => [
        {
          id: crypto.randomUUID(),
          entityType: 'shared_reservation' as const,
          entityId: sr.id,
          operation: 'create' as const,
          data: {
            id: sr.id,
            saunaId: sr.saunaId,
            date: sr.date.toISOString().split('T')[0],
            startTime: sr.startTime.toISOString(),
            malesDurationHours: sr.malesDurationHours,
            femalesDurationHours: sr.femalesDurationHours,
            genderOrder: sr.genderOrder,
            name: sr.name,
            description: sr.description,
            isAutoGenerated: sr.isAutoGenerated,
            autoCancelledAt: sr.autoCancelledAt?.toISOString() || null,
            convertedToIndividual: sr.convertedToIndividual,
          },
          timestamp: sr.updatedAt,
        },
        ...sr.participants.map((p) => ({
          id: crypto.randomUUID(),
          entityType: 'shared_participant' as const,
          entityId: p.id,
          operation: 'create' as const,
          data: {
            id: p.id,
            sharedReservationId: p.sharedReservationId,
            boatId: p.boatId,
            adults: p.adults,
            kids: p.kids,
            joinedAt: p.joinedAt.toISOString(),
          },
          timestamp: p.joinedAt,
        })),
      ]),
    ];

    // Step 3: Update device last sync timestamp
    await prisma.islandDevice.update({
      where: { id: deviceId },
      data: { lastSyncAt: new Date() },
    });

    // Return combined result
    return successResponse({
      success: true,
      appliedChanges,
      rejectedChanges,
      serverChanges,
      newSyncTimestamp: new Date(),
    });
  } catch (error) {
    return handleApiError(error);
  }
}
